### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by shakeelmohamed** [shakeelmohamed/youtube-watch-later#1]
- [x] simplify everything to index.html
- [ ] use official JS library to cleanup the code
- [ ] UI (added primer CSS)
- [ ] make a logo
- [ ] show video duration & author
- [ ] does it work for any playlist? if so, rename
- [ ] Move the repo to the watchlater org
- [ ] add support for [removing videos from playlist](https://developers.google.com/youtube/v3/docs/playlistItems/delete) (will require additional permissions, hold off for now)

**Comment by shakeelmohamed** [comment]
Impossible now due to #2
